### PR TITLE
bugfix/#4930 - pricing page - Add Location - active cities en translate

### LINKED ISSUE #4930: [Pricing Page. Add location] 'Active cities' - 'EN' selected language - are displayed in Ukrainian
**Environment:** Windows 10 Pro, Google Chrome 105.0.5195.127
**Reproducible:** always
**Build found:** 10.01.2023

**Preconditions**
The user should be authorized as UBS Admin
Select 'EN' language

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/GreenCityClient/#/ubs-admin/tariffs
2. Click on 'Gear'
3. Click on Tab 'Add'
4. Click on Tab  'Location'
5. Write Some region with active cities (like 'Kharkiv Oblast').
6. Click on 'Active cities'

**Actual result**
Active cities are displayed in Ukrainian
image
Error message is absent when user enters active city
image

**Expected result**
Active cities are displayed in English
Error message displayed when user enters active city

### PR DESCRIPTION
**Pull request by atsa21**
- UBS Admin - Pricing page - Add Location pop up - added translation for active cities.
- Fixed error message logic for en city input - if city is active

### CODE REVIEW

File: src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts [hunk 1]
```diff
@@ -81,6 +81,7 @@ export class UbsAdminTariffsLocationPopUpComponent implements OnInit, AfterViewC
   cityExist = false;
   editedCityExist = false;
   cities = [];
+  activeCities = [];
```
Comment (hnativlyubomyr) [inline src/app/ubs/ubs-admin/components/ubs-admin-tariffs/ubs-admin-tariffs-location-pop-up/ubs-admin-tariffs-location-pop-up.component.ts:84]: I would use a getter for activeCities

**Review by hnativlyubomyr — APPROVED** [review]

**Review by vplvua — APPROVED** [review]

**Review by AngelinaRudnitska — APPROVED** [review]

**Review by SokhaTaras — APPROVED** [review]

**Review by marianaharnyk — APPROVED** [review]

**Review by katia9261 — APPROVED** [review]
