### PR TITLE
Bugfix/#5876 - UBS Admin - Order table and Certificates export excel selected

### LINKED ISSUE #5876: [Prod. UBS Admin] Order table and Certificates page - it is impossible to "Export to Excel" selected rows
**Environment:** Windows 10 Pro, Google Chrome 111.0.5563.65
**Reproducible:** always
**Build found:** 01.06.2023

**Preconditions**
User is authorized as Admin

**Steps to reproduce**
1. Go to https://www.testgreencity.ga/#/ubs-admin/orders
2. Click on any check-box on the table
3. Click on "Export to Excel"

**Actual result**
Admin can't save selected data
The same for Certificates page
image

**Expected result**
Admin can save selected data

### PR DESCRIPTION
**Pull request by atsa21**
UBS Admin

- Added possibility to export to Excel selected rows by check-box

### CODE REVIEW

**Review by NadiiaStoiko — APPROVED** [review]

**Review by hnativlyubomyr — APPROVED** [review]

File: src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table-excel-popup/ubs-admin-table-excel-popup.component.ts [hunk 1]
```diff
@@ -112,6 +117,16 @@ export class UbsAdminTableExcelPopupComponent implements OnInit {
           });
       }
     }
+    if (this.tableView === tableViewParameters.selectedOrders && this.name === nameOfTable.ordersTable) {
```
Comment (hnativlyubomyr) [inline src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table-excel-popup/ubs-admin-table-excel-popup.component.ts]: I would create a constant для 
this.tableView === tableViewParameters.selectedOrders
because it is used more than once

Comment (atsa21) [reply src/app/ubs/ubs-admin/components/ubs-admin-table/ubs-admin-table-excel-popup/ubs-admin-table-excel-popup.component.ts]: Added, thanks )

**Review by ruslan-teh — APPROVED** [review]

**Review by AlexW8719 — APPROVED** [review]

**Review by katia9261 — APPROVED** [review]
