### PR TITLE
Bugfix/#5488 my habits sort from last added habit

### LINKED ISSUE #5488: [Habits view] The list of habits 'In progress'/'Acquired' is formed by habits id
**Environment:** 11 Home, Google Chrome.
**Reproducible:** always.
**Build found:** 17.03.23

**Preconditions**

1. Registered User is logged in
2. User has at least two habit in progress

**Steps to reproduce**
1. Verify if the list of habits 'In progress'/'Acquired' are formed by habits id

**Actual result**
The list of habits 'In progress'/'Acquired' is formed by habits id.

https://user-images.githubusercontent.com/107051540/225910332-2eee0533-1a55-4edb-91c5-ee5d88260ad7.mp4

**Expected result**
The list of habits 'In progress'/'Acquired' should form by date in order from the latest to earliest habits.

### PR DESCRIPTION
**Pull request by atsa21**
- Changed habit sorting on My Space - from ASC to **sort by creation data**

### CODE REVIEW

**Review by katia9261 — APPROVED** [review]

**Review by NadiiaStoiko — APPROVED** [review]

File: src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.ts [hunk 1]
```diff
@@ -164,14 +164,14 @@ export class ProfileDashboardComponent implements OnInit, OnDestroy {
...
-      }
-      if (secondHabit.habit.id > firstHabit.habit.id) {
+      if (firstHabit.createDateTime > secondHabit.createDateTime) {
         return -1;
       }
+      if (secondHabit.createDateTime > firstHabit.createDateTime) {
+        return 1;
+      }
       return 0;
     });
```
Comment (hnativlyubomyr) [inline src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.ts:170]: I would simplify it:
return firstHabit.createDateTime > secondHabit.createDateTime ? -1 : 1

Comment (atsa21) [reply src/app/main/component/user/components/profile/profile-dashboard/profile-dashboard.component.ts:170]: Thank you. Already fixed

**Review by KKatiaa — APPROVED** [review]

**Review by hnativlyubomyr — APPROVED** [review]

**Review by ruslan-teh — APPROVED** [review]

**Review by hnativlyubomyr — APPROVED** [review]
