### PR TITLE
Bugfix/#4250 homepage buttons start forming a habit

### LINKED ISSUE #4250: [Home Page] "Start forming a habit!" Buttons don't have the same functionality
**Environment:** All Browsers
**Reproducible:** always.

Step to reproduce:

Scenario #1:

1). Go to [GreenCity (ita-social-projects.github.io)](https://ita-social-projects.github.io/GreenCityClient/#/)
2). Log in as a user
3). Click on every "Start forming a habit!" Button

Actual result:
Logged in User is  on "Home" Page after clicking on second and third button "Start forming a habit!"

Expected result:
Logged in User should be navigated to "My Space" Page

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Major"), Type ("Functional")

### PR DESCRIPTION
**Pull request by atsa21**
Fixed redirection on click 'Start forming a habit!' buttons on Homepage.

### CODE REVIEW

File: src/app/main/component/home/components/stat-row/stat-row.component.ts [hunk 1]
```diff
@@ -1,14 +1,29 @@
...
+
   readonly locationImage = 'assets/img/icon/location-icon.png';
+
+  constructor(private router: Router, private checkTokenservice: CheckTokenService, private localService: LocalStorageService) {}
+
+  ngOnInit() {
+    this.localService.userIdBehaviourSubject.subscribe((userId) => (this.userId = userId));
+  }
+
+  startHabit() {
```
Comment (hnativlyubomyr) [inline src/app/main/component/home/components/stat-row/stat-row.component.ts]: add return type void

**Review by hnativlyubomyr — APPROVED** [review]

File: src/app/main/component/home/components/stat-row/stat-row.component.ts (hunk 1 above)
Comment (atsa21) [reply src/app/main/component/home/components/stat-row/stat-row.component.ts]: You're right, I will add it

**Review by katia9261 — APPROVED** [review]

**Review by vplvua — APPROVED** [review]

**Review by marianaharnyk — APPROVED** [review]

**Review by zaitsev-oleksii — APPROVED** [review]
