### PR TITLE
[Bugfix] #7306 Update image path for habits

### LINKED ISSUE #7306: [Events] Do Not load events when scroll
**Events are not loading properly when scrolling infinitely on the events page.** 

**Environment:** 
- **Operating System:** Windows 10
- **Browser:** Google Chrome
- **Reproducibility:** Always

**Preconditions:**
1. Authenticated user.
2. On the Green City.
3. On the "Events" page.

**Steps to Reproduce:**
1. Navigate to the "Events" page.
2. Scroll down to load more events.

**Expected Result:**
- Additional events should load as the user scrolls down.

**Actual Result:**
- No additional events load, causing the list to remain static.
Screenshot (1087)

### PR DESCRIPTION
**Pull request by Lokankara**
[7306](https://github.com/ita-social-projects/GreenCity/issues/7306)

### CODE REVIEW

File: src/app/main/component/events/components/event-details/event-details.component.ts [hunk 1]
```diff
@@ -144,9 +136,7 @@ export class EventDetailsComponent implements OnInit, OnDestroy {
   }
 
   bindUserName(): void {
-    this.userNameSub = this.localStorageService.firstNameBehaviourSubject.subscribe((name) => {
-      this.organizerName = name;
-    });
+    this.localStorageService.firstNameBehaviourSubject.subscribe((name) => (this.organizerName = name));
```
Comment (dmytro-kryvyi) [inline src/app/main/component/events/components/event-details/event-details.component.ts]: Please add takeUntill() or take(1) according to functionality

File: src/app/main/component/events/components/event-details/event-details.component.ts [hunk 2]
```diff
@@ -319,17 +308,6 @@ export class EventDetailsComponent implements OnInit, OnDestroy {
     this.destroy.unsubscribe();
   }
 
-  private formatDates(): void {
```
Comment (dmytro-kryvyi) [inline src/app/main/component/events/components/event-details/event-details.component.ts:320]: Please remove the commented code

File: src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.ts [hunk 3]
```diff
@@ -11,6 +11,7 @@ import { HabitAssignInterface } from '@global-user/components/habit/models/inter
 import { FriendProfilePicturesArrayModel } from '@global-user/models/friend.model';
 import { MatDialog } from '@angular/material/dialog';
 import { FriendsListPopUpComponent } from '@global-user/components/shared/components/friends-list-pop-up/friends-list-pop-up.component';
+import { habitImages } from '../../../../../../image-pathes/habits-images';
```
Comment (dmytro-kryvyi) [inline src/app/main/component/user/components/profile/profile-dashboard/one-habit/one-habit.component.ts]: Not an issue just prefer non-relative pathes for imports to avoid ../ (Can be configured in IDE)

**Review by dmytro-kryvyi — APPROVED** [review]

**Review by hnativlyubomyr — APPROVED** [review]
